name: Update README all day at 04:04
on:
  push:
  workflow_dispatch:
  schedule:
    # “At 13:37 on every day-of-week from Monday through Friday.”
    - cron: '04 4 * * *'
jobs:
  update-readme:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Update README.md file
        run: |
          node index.js > README.md
        env:
          CI: true
      - name: commit changes
        uses: EndBug/add-and-commit@v9
        with:
          # The name of the user that will be displayed as the author of the commit.
          # Default: depends on the default_author input
          author_name: s-jdd
          # The email of the user that will be displayed as the author of the commit.
          # Default: depends on the default_author input
          author_email: ${{ secrets.EMAIL }}
          force: false
          signoff: false
          # The message for the commit.
          # Default: 'Commit from GitHub Actions (name of the workflow)'
          message: ':memo: README.md updated by Gitbot'
        env:
          # This is necessary in order to push a commit to the repo
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
